name: login_screen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.4
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  google_sign_in: ^6.2.1
  lottie: ^3.0.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/bg.jpg
  - assets/images/google.png

  - assets/lottie_json/
