name: login_screen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/bg.jpg
  - assets/images/google.png
  - assets/lottie/pandaWithHeadphones.json
  - assets/lottie/musicRhythm.json
  - assets/lottie/notes.json
