// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsgsjkmGDeeii2rPKeetjqERLfJG9FarQ',
    appId: '1:163667344350:web:bddaf762e42ffa283d3b4f',
    messagingSenderId: '163667344350',
    projectId: 'login-a27df',
    authDomain: 'login-a27df.firebaseapp.com',
    storageBucket: 'login-a27df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEU_Yu1VkRjRRBLkdnXxcjJKxnQH-wBRg',
    appId: '1:163667344350:android:50c4de806c6bf2ba3d3b4f',
    messagingSenderId: '163667344350',
    projectId: 'login-a27df',
    storageBucket: 'login-a27df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC9dvR5ROd-ZkStexfPF2LreDZIi7_Fao',
    appId: '1:163667344350:ios:e3b3da68b711ad533d3b4f',
    messagingSenderId: '163667344350',
    projectId: 'login-a27df',
    storageBucket: 'login-a27df.appspot.com',
    iosBundleId: 'com.example.loginScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC9dvR5ROd-ZkStexfPF2LreDZIi7_Fao',
    appId: '1:163667344350:ios:3639e6ff04c322bd3d3b4f',
    messagingSenderId: '163667344350',
    projectId: 'login-a27df',
    storageBucket: 'login-a27df.appspot.com',
    iosBundleId: 'com.example.loginScreen.RunnerTests',
  );
}
